//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasMateria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotasMateria()
        {
            this.PersonaMateria = new HashSet<PersonaMateria>();
        }
    
        public int Id { get; set; }
        public double Notas { get; set; }
        public int Periodo_Id { get; set; }
        public int Materia_id { get; set; }
        public int Estudiante_id { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<PersonaMateria> PersonaMateria { get; set; }
        public  Periodo Periodo { get; set; }
    }
}
