//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaMateria
    {
        public int Id { get; set; }
        public int Materia_Id { get; set; }
        public int Persona_Id { get; set; }
        public Nullable<int> Notas_Materias_Id { get; set; }
    
        public  Persona Persona { get; set; }
        public  Materia Materias { get; set; }
        public  NotasMateria NotasMaterias { get; set; }
    }
}
