//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SSDBV2Container : DbContext
    {
        public SSDBV2Container()
            : base("name=SSDBV2Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<PersonaMateria> PersonaMaterias { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<NotasMateria> NotasMaterias { get; set; }
        public virtual DbSet<TDoc> TDocs { get; set; }
        public virtual DbSet<TipoPersona> TipoPersonas { get; set; }
        public virtual DbSet<Periodo> Periodoes { get; set; }
    }
}
